adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/CategoryController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/LoginUserController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/QuestionController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/StudentController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/StudentModelController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/SubjectController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/TutorialController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/model/LoginUser.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/repository/LoginUserRepository.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/service/CommintService.java
adarsh/tutorial/server/src/test/java/com/example/postgresdemo/controller/CommentControllerTest.java

backend assessment

---

shashi/tutorial/client/src/app/components/userlogin/userlogin.component.html
shashi/tutorial/client/src/app/components/userlogin/userlogin.component.ts
shashi/tutorial/client/src/app/services/tutorial.service.ts

user login commit code

---

adarsh/tutorial/clint/karma.conf.js
adarsh/tutorial/clint/src/app/app-routing.module.ts
adarsh/tutorial/clint/src/app/app.component.html
adarsh/tutorial/clint/src/app/app.module.ts
adarsh/tutorial/clint/src/app/components/login/login.component.html
adarsh/tutorial/clint/src/app/components/login/login.component.spec.ts
adarsh/tutorial/clint/src/app/components/login/login.component.ts
adarsh/tutorial/clint/src/app/components/tutorial-view-detials/comment-post/comment-post.component.html
adarsh/tutorial/clint/src/app/components/tutorial-view-detials/comment-post/commentPost.component.ts
adarsh/tutorial/clint/src/app/components/tutorial-view-detials/tutorial-view-detials.component.html
adarsh/tutorial/clint/src/app/components/tutorial-view-detials/tutorial-view-detials.component.ts
adarsh/tutorial/clint/src/app/models/loginUser.model.ts
adarsh/tutorial/clint/src/app/services/tutorial.service.ts
adarsh/tutorial/server/pom.xml
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/controller/LoginUserController.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/model/Comment.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/model/LoginUser.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/service/CommintService.java
adarsh/tutorial/server/src/main/java/com/example/postgresdemo/service/LoginUserService.java
adarsh/tutorial/server/src/test/java/com/example/postgresdemo/controller/CommentControllerTest.java

backend commit

---

shashi/tutorial/server/src/repositories/userlogin.repository.test.ts
shashi/tutorial/server/test/utils/generate.ts

jest for Userlogin

---

druthvik/tutorial/server/src/repositories/userlogin.repository.test.ts
druthvik/tutorial/server/src/repositories/userlogin.repository.ts

jest testing userlogin

---

shashi/report/backend/src/repositories/panel.repository.test.ts
shashi/report/backend/test/utils/generate.ts
shashi/report/frontend/src/app/app-routing.module.ts
shashi/report/frontend/src/app/app.component.html
shashi/report/frontend/src/app/app.module.ts
shashi/report/frontend/src/app/components/add-panel/add-panel.component.html
shashi/report/frontend/src/app/components/add-panel/add-panel.component.spec.ts
shashi/report/frontend/src/app/components/add-panel/add-panel.component.ts
shashi/report/frontend/src/app/components/panel-list/panel-list.component.css
shashi/report/frontend/src/app/components/panel-list/panel-list.component.html
shashi/report/frontend/src/app/components/panel-list/panel-list.component.ts
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.css
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.html
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.spec.ts
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.ts

report task test's dropdown,add test to panel and update panel code PR

report task test's dropdown,add test to panel and update panel code

---

druthvik/Report/client/src/app/app-routing.module.ts
druthvik/Report/client/src/app/app.module.ts
druthvik/Report/client/src/app/components/addpanel/addpanel.component.css
druthvik/Report/client/src/app/components/addpanel/addpanel.component.html
druthvik/Report/client/src/app/components/addpanel/addpanel.component.spec.ts
druthvik/Report/client/src/app/components/addpanel/addpanel.component.ts
druthvik/Report/client/src/app/components/editpanel/editpanel.component.css
druthvik/Report/client/src/app/components/editpanel/editpanel.component.html
druthvik/Report/client/src/app/components/editpanel/editpanel.component.spec.ts
druthvik/Report/client/src/app/components/editpanel/editpanel.component.ts
druthvik/Report/client/src/app/components/page-not-found/page-not-found.component.html
druthvik/Report/client/src/app/components/page-not-found/page-not-found.component.spec.ts
druthvik/Report/client/src/app/components/page-not-found/page-not-found.component.ts
druthvik/Report/client/src/app/components/panel-list/panel-list.component.css
druthvik/Report/client/src/app/components/panel-list/panel-list.component.html
druthvik/Report/client/src/app/components/panel-list/panel-list.component.ts
druthvik/Report/client/src/app/components/reporttable/reporttable.component.html
druthvik/Report/client/src/app/components/reporttable/reporttable.component.spec.ts
druthvik/Report/client/src/app/components/reporttable/reporttable.component.ts
druthvik/Report/client/src/app/services/panel.service.ts
druthvik/Report/server/public/swagger.json
druthvik/Report/server/src/controllers/panel.controller.ts
druthvik/Report/server/src/repositories/panel.repository.test.ts
druthvik/Report/server/src/repositories/panel.repository.ts
druthvik/Report/server/src/routes/panel.router.ts
druthvik/Report/server/test/utils/generate.ts

Report Task

---

shashi/report/backend/src/controllers/reportpaneltest.controller.ts
shashi/report/backend/src/models/reportpaneltest.ts
shashi/report/backend/src/routes/reportpaneltest.router.ts
shashi/report/frontend/src/app/components/report-list/report-list.component.html
shashi/report/frontend/src/app/components/report-list/report-list.component.ts
shashi/report/frontend/src/app/components/report/report.component.html
shashi/report/frontend/src/app/components/report/report.component.ts
shashi/report/frontend/src/app/models/reportpaneltest.model.ts

pr of printing data inside text box

Textbox data

---

shashi/report/backend/src/controllers/reportpaneltest.controller.ts
shashi/report/backend/src/models/reportpaneltest.ts
shashi/report/backend/src/repositories/panel.repository.test.ts
shashi/report/backend/src/routes/reportpaneltest.router.ts
shashi/report/backend/test/utils/generate.ts
shashi/report/frontend/src/app/app-routing.module.ts
shashi/report/frontend/src/app/app.component.html
shashi/report/frontend/src/app/app.module.ts
shashi/report/frontend/src/app/components/add-panel/add-panel.component.html
shashi/report/frontend/src/app/components/add-panel/add-panel.component.spec.ts
shashi/report/frontend/src/app/components/add-panel/add-panel.component.ts
shashi/report/frontend/src/app/components/panel-list/panel-list.component.css
shashi/report/frontend/src/app/components/panel-list/panel-list.component.html
shashi/report/frontend/src/app/components/panel-list/panel-list.component.ts
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.css
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.html
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.spec.ts
shashi/report/frontend/src/app/components/panel-test-details/panel-test-details.component.ts
shashi/report/frontend/src/app/components/report-list/report-list.component.html
shashi/report/frontend/src/app/components/report-list/report-list.component.ts
shashi/report/frontend/src/app/components/report/report.component.html
shashi/report/frontend/src/app/components/report/report.component.ts
shashi/report/frontend/src/app/models/reportpaneltest.model.ts

panelReportTest table data binding pr

pr of reportlisting,save report and edit report

---

shashi/report/backend/src/controllers/test.controller.ts
shashi/report/backend/src/models/panels.ts
shashi/report/frontend/src/app/components/chart/chart.component.css
shashi/report/frontend/src/app/components/chart/chart.component.html
shashi/report/frontend/src/app/components/chart/chart.component.ts

Employee chart

---

shashi/report/backend/src/controllers/fileupload.controller.ts
shashi/report/backend/src/controllers/panel.controller.ts
shashi/report/backend/src/models/fileupload.ts
shashi/report/backend/src/repositories/panel.repository.ts
shashi/report/backend/src/routes/fileupload.router.ts
shashi/report/backend/src/routes/panel.router.ts
shashi/report/frontend/src/app/components/chart/chart.component.ts
shashi/report/frontend/src/app/components/datatables/datatables.component.html
shashi/report/frontend/src/app/components/datatables/datatables.component.ts
shashi/report/frontend/src/app/components/panel-list/panel-list.component.html
shashi/report/frontend/src/app/components/panel-list/panel-list.component.ts
shashi/report/frontend/src/app/services/panel.serveice.ts

Nestjs api

---

shashi/report/frontend/src/app/components/chart/chart.component.ts

sample testing commit

---

shashi/report/frontend/src/app/components/chart/chart.component.ts
shashi/report/frontend/src/app/components/datatables/datatables.component.html
shashi/report/frontend/src/app/components/datatables/datatables.component.ts
shashi/report/frontend/src/app/services/panel.serveice.ts

Pagination branch

---

shashi/report/backend/src/controllers/fileupload.controller.ts
shashi/report/backend/src/controllers/panel.controller.ts
shashi/report/backend/src/models/fileupload.ts
shashi/report/backend/src/repositories/panel.repository.ts
shashi/report/backend/src/routes/fileupload.router.ts
shashi/report/backend/src/routes/panel.router.ts
shashi/report/frontend/src/app/components/chart/chart.component.ts
shashi/report/frontend/src/app/components/datatables/datatables.component.html
shashi/report/frontend/src/app/components/datatables/datatables.component.ts
shashi/report/frontend/src/app/services/panel.serveice.ts

map() for post api both frontend and backend

File upload download branch

---

shashi/report/backend/src/controllers/fileupload.controller.ts
shashi/report/backend/src/controllers/panel.controller.ts
shashi/report/backend/src/models/fileupload.ts
shashi/report/backend/src/repositories/panel.repository.ts
shashi/report/backend/src/routes/fileupload.router.ts
shashi/report/backend/src/routes/panel.router.ts
shashi/report/frontend/src/app/components/chart/chart.component.ts
shashi/report/frontend/src/app/components/datatables/datatables.component.html
shashi/report/frontend/src/app/components/datatables/datatables.component.ts
shashi/report/frontend/src/app/components/panel-list/panel-list.component.html
shashi/report/frontend/src/app/components/panel-list/panel-list.component.ts
shashi/report/frontend/src/app/services/panel.serveice.ts

Search panel branch

---

shashi/nestJs/backend/src/app.controller.ts
shashi/nestJs/backend/src/app.module.ts
shashi/nestJs/backend/src/app.service.ts
shashi/nestJs/backend/src/articles/dto/article.dto.ts
shashi/nestJs/backend/src/main.ts
shashi/report/backend/src/controllers/fileupload.controller.ts
shashi/report/backend/src/controllers/panel.controller.ts
shashi/report/backend/src/models/fileupload.ts
shashi/report/backend/src/repositories/panel.repository.ts
shashi/report/backend/src/routes/fileupload.router.ts
shashi/report/backend/src/routes/panel.router.ts
shashi/report/frontend/src/app/components/chart/chart.component.ts
shashi/report/frontend/src/app/components/datatables/datatables.component.html
shashi/report/frontend/src/app/components/datatables/datatables.component.ts
shashi/report/frontend/src/app/components/panel-list/panel-list.component.html
shashi/report/frontend/src/app/components/panel-list/panel-list.component.ts
shashi/report/frontend/src/app/services/panel.serveice.ts

Nestjs branch

---

adarsh/reports/server/check.json
adarsh/reports/server/pom.xml
adarsh/reports/server/src/main/java/com/example/onetoonemapping/SpringBootJpaOneToOneHibernateMappingExampleApplication.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelController.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelDataController.java
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.ts
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.html
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.spec.ts
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.ts

Adarsh data table chart

---

adarsh/reports/server/check.json
adarsh/reports/server/pom.xml
adarsh/reports/server/src/main/java/com/example/onetoonemapping/SpringBootJpaOneToOneHibernateMappingExampleApplication.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelController.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelDataController.java
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.html
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.spec.ts
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.ts
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.html
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.spec.ts
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.ts
adarsh/tutorial/clint/src/app/models/person.model.ts
adarsh/tutorial/clint/src/app/models/student.model.ts
adarsh/tutorial/clint/typings.json

Adarsh multi axies chart

---

adarsh/reports/server/check.json
adarsh/reports/server/pom.xml
adarsh/reports/server/src/main/java/com/example/onetoonemapping/SpringBootJpaOneToOneHibernateMappingExampleApplication.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/Pagination.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelController.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelDataController.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/models/TestData.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/repository/PanelRepository.java
adarsh/reports/server/src/main/java/com/example/onetoonemapping/service/PanelService.java
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.html
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.spec.ts
adarsh/tutorial/clint/src/app/components/data-table/data-table.component.ts
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.html
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.spec.ts
adarsh/tutorial/clint/src/app/components/pagination-table/pagination-table.component.ts
adarsh/tutorial/clint/src/app/models/person.model.ts
adarsh/tutorial/clint/src/app/models/student.model.ts
adarsh/tutorial/clint/typings.json

Adarsh pagination

---

adarsh/reports/client/src/app/components/panel-list/panel-list.component.html
adarsh/reports/client/src/app/components/panel-list/panel-list.component.ts
adarsh/reports/server/src/main/java/com/example/onetoonemapping/controller/PanelController.java

commit on search box

---

shashi/bootstrap/js/data.js
shashi/bootstrap/js/main.js
shashi/bootstrap/test1/css/test1.css
shashi/bootstrap/test1/js/data.js
shashi/bootstrap/test1/js/main.js
shashi/bootstrap/test1/test1.html
shashi/bootstrap/test2/css/test2.css
shashi/bootstrap/test2/test2.html

bootstrap commit pr

---

shashi/customer/.gitignore

customer initial commit

---

adarsh/coustmer/client/src/app/app-routing.module.ts
adarsh/coustmer/client/src/app/app.component.html
adarsh/coustmer/client/src/app/app.module.ts
adarsh/coustmer/client/src/app/components/user-login/user-login.component.css
adarsh/coustmer/client/src/app/components/user-login/user-login.component.html
adarsh/coustmer/client/src/app/components/user-login/user-login.component.spec.ts
adarsh/coustmer/client/src/app/components/user-login/user-login.component.ts
adarsh/coustmer/client/src/app/models/loginUser.ts

commit on customer login

---

adarsh/coustmer/client/src/app/components/script.js
adarsh/coustmer/client/src/app/components/user-login/script.js
adarsh/coustmer/client/src/app/components/user-login/style.css
adarsh/coustmer/client/src/app/components/user-registration/user-registration.component.css
adarsh/coustmer/client/src/app/components/user-registration/user-registration.component.html
adarsh/coustmer/client/src/app/components/user-registration/user-registration.component.spec.ts
adarsh/coustmer/client/src/app/components/user-registration/user-registration.component.ts
adarsh/coustmer/client/src/app/models/user.model.ts
adarsh/coustmer/client/src/app/services/custmer.service.spec.ts
adarsh/coustmer/client/src/app/services/custmer.service.ts
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/controller/UserController.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/models/User.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/repository/UserRepository.java
adarsh/coustmer/server/src/main/resources/application.properties

commit on customer registration

Adarsh register customer

---

shashi/customer/client/src/app/app.module.ts
shashi/customer/client/src/app/components/user-registration/user-registration.component.html
shashi/customer/client/src/app/components/userLogin/userlogin.component.html
shashi/customer/client/src/app/components/userLogin/userlogin.component.ts
shashi/customer/server/src/controllers/userlogin.controller.ts
shashi/customer/server/src/repositories/userlogin.repository.ts
shashi/customer/server/src/routes/userLogin.router.ts

password authentication commit(tried) pr

password authentication commit(tried)

---

shashi/customer/client/src/app/app-routing.module.ts
shashi/customer/client/src/app/app.component.html
shashi/customer/client/src/app/app.module.ts
shashi/customer/client/src/app/components/customerList/customer.component.html
shashi/customer/client/src/app/components/customerList/customer.component.spec.ts
shashi/customer/client/src/app/components/customerList/customer.component.ts
shashi/customer/client/src/app/models/customer.model.ts
shashi/customer/client/src/app/services/customerservice.ts
shashi/customer/server/src/config/database.ts
shashi/customer/server/src/controllers/customer.controller.ts
shashi/customer/server/src/models/customer.ts
shashi/customer/server/src/models/index.ts
shashi/customer/server/src/repositories/customer.repository.ts
shashi/customer/server/src/routes/customer.route.ts
shashi/customer/server/src/routes/index.ts

customer list code commit

---

shashi/customer/client/src/app/app-routing.module.ts
shashi/customer/client/src/app/app.component.html
shashi/customer/client/src/app/app.module.ts
shashi/customer/client/src/app/components/create-customer/create-customer.component.html
shashi/customer/client/src/app/components/create-customer/create-customer.component.spec.ts
shashi/customer/client/src/app/components/create-customer/create-customer.component.ts
shashi/customer/client/src/app/components/customerList/customer.component.html
shashi/customer/client/src/app/components/customerList/customer.component.spec.ts
shashi/customer/client/src/app/components/customerList/customer.component.ts
shashi/customer/client/src/app/components/customerList/customerList.component.html
shashi/customer/client/src/app/components/customerList/customerList.component.spec.ts
shashi/customer/client/src/app/components/customerList/customerList.component.ts
shashi/customer/client/src/app/components/user-registration/user-registration.component.html
shashi/customer/client/src/app/models/customer.model.ts
shashi/customer/client/src/app/services/customerservice.ts
shashi/customer/server/src/config/database.ts
shashi/customer/server/src/controllers/customer.controller.ts
shashi/customer/server/src/models/customer.ts
shashi/customer/server/src/models/index.ts
shashi/customer/server/src/repositories/customer.repository.ts
shashi/customer/server/src/routes/customer.route.ts
shashi/customer/server/src/routes/index.ts

Shashi create customer frontend code pr

Shashi create customer

---

shashi/customer/client/src/app/app-routing.module.ts
shashi/customer/client/src/app/app.component.html
shashi/customer/client/src/app/app.module.ts
shashi/customer/client/src/app/components/create-customer/create-customer.component.html
shashi/customer/client/src/app/components/create-customer/create-customer.component.spec.ts
shashi/customer/client/src/app/components/create-customer/create-customer.component.ts
shashi/customer/client/src/app/components/customerList/customer.component.html
shashi/customer/client/src/app/components/customerList/customer.component.spec.ts
shashi/customer/client/src/app/components/customerList/customer.component.ts
shashi/customer/client/src/app/components/customerList/customerList.component.html
shashi/customer/client/src/app/components/customerList/customerList.component.spec.ts
shashi/customer/client/src/app/components/customerList/customerList.component.ts
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.css
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.html
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.spec.ts
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.ts
shashi/customer/client/src/app/components/user-registration/user-registration.component.html
shashi/customer/client/src/app/models/customer.model.ts
shashi/customer/client/src/app/services/customerservice.ts
shashi/customer/server/src/config/database.ts
shashi/customer/server/src/controllers/customer.controller.ts
shashi/customer/server/src/models/customer.ts
shashi/customer/server/src/models/index.ts
shashi/customer/server/src/repositories/customer.repository.ts
shashi/customer/server/src/routes/customer.route.ts
shashi/customer/server/src/routes/index.ts

Shashi edit customer frontend code pr

Shashi edit customer

---

shashi/customer/client/src/app/app-routing.module.ts
shashi/customer/client/src/app/app.component.html
shashi/customer/client/src/app/app.module.ts
shashi/customer/client/src/app/components/create-customer/create-customer.component.html
shashi/customer/client/src/app/components/create-customer/create-customer.component.spec.ts
shashi/customer/client/src/app/components/create-customer/create-customer.component.ts
shashi/customer/client/src/app/components/customerList/customer.component.html
shashi/customer/client/src/app/components/customerList/customer.component.spec.ts
shashi/customer/client/src/app/components/customerList/customer.component.ts
shashi/customer/client/src/app/components/customerList/customerList.component.html
shashi/customer/client/src/app/components/customerList/customerList.component.spec.ts
shashi/customer/client/src/app/components/customerList/customerList.component.ts
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.css
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.html
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.spec.ts
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.ts
shashi/customer/client/src/app/components/user-registration/user-registration.component.html
shashi/customer/client/src/app/models/customer.model.ts
shashi/customer/client/src/app/services/customerservice.ts
shashi/customer/server/src/config/database.ts
shashi/customer/server/src/controllers/customer.controller.ts
shashi/customer/server/src/controllers/customerGroup.controller.ts
shashi/customer/server/src/models/customer.ts
shashi/customer/server/src/models/customerGroup.ts
shashi/customer/server/src/models/index.ts
shashi/customer/server/src/repositories/customer.repository.ts
shashi/customer/server/src/repositories/customerGroup.repository.ts
shashi/customer/server/src/routes/customer.route.ts
shashi/customer/server/src/routes/customerGroup.router.ts
shashi/customer/server/src/routes/index.ts

Shashi customer group list backend code pr

Shashi customer group

---

adarsh/coustmer/client/src/app/components/add-customer-group/add-customer-group.component.html
adarsh/coustmer/client/src/app/components/add-customer-group/add-customer-group.component.spec.ts
adarsh/coustmer/client/src/app/components/add-customer-group/add-customer-group.component.ts
adarsh/coustmer/client/src/app/models/customergroup.ts
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/models/Customar.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/models/CustomerGroup.java

commit on customer group creation

Adarsh create customer group

---

shashi/customer/client/src/app/app.component.html
shashi/customer/client/src/app/components/create-customer/create-customer.component.html
shashi/customer/client/src/app/components/create-customer/create-customer.component.ts
shashi/customer/client/src/app/components/edit-customer-group/edit-customer-group.component.css
shashi/customer/client/src/app/components/edit-customer-group/edit-customer-group.component.html
shashi/customer/client/src/app/components/edit-customer-group/edit-customer-group.component.ts
shashi/customer/client/src/app/components/edit-customer/edit-customer.component.ts

edit customergroup final commit pr

edit customergroup final commit

---

adarsh/coustmer/server/pom.xml
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/SpringBootJpaCoustmerMappingExampleApplication.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/config/MailConfiguration.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/controller/CustomerController.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/controller/CustomerGroupController.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/controller/EmailCntroller.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/models/CustomerEmail.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/models/CustomerGroup.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/models/Mail.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/repository/CustomerGroupRepository.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/service/MailService.java
adarsh/coustmer/server/src/main/java/com/example/onetoonemapping/service/MailServiceImpl.java
adarsh/coustmer/server/src/main/resources/adarsh.html
adarsh/coustmer/server/src/main/resources/application.properties

commit on sending mail to customer

commit on email sanding

---

shashi/company-department/client/src/app/app-routing.module.ts
shashi/company-department/client/src/app/app.component.html
shashi/company-department/client/src/app/app.module.ts
shashi/company-department/client/src/app/components/company-list/company-list.component.html
shashi/company-department/client/src/app/components/company-list/company-list.component.spec.ts
shashi/company-department/client/src/app/components/company-list/company-list.component.ts
shashi/company-department/client/src/app/components/create-company/create-company.component.html
shashi/company-department/client/src/app/services/companyDepartment.service.ts
shashi/company-department/nestjs-server/src/company/company.controller.ts
shashi/company-department/nestjs-server/src/company/company.service.ts

company listing frontend code pr

company listing backend commit

---

shashi/company-department/client/src/app/components/company-list/company-list.component.css
shashi/company-department/client/src/app/components/create-company/create-company.component.css
shashi/company-department/client/src/app/components/create-company/create-company.component.html
shashi/company-department/client/src/app/components/create-company/create-company.component.ts
shashi/company-department/client/src/app/components/department-list/department-list.component.css
shashi/company-department/client/src/app/components/department-list/department-list.component.ts

departments list check boxes in create company component code pr

departments list check boxes in create company component code commit

---

shashi/company-department/client/src/app/components/create-company/create-company.component.html
shashi/company-department/client/src/app/components/create-company/create-company.component.ts
shashi/company-department/nestjs-server/src/company/company.controller.ts
shashi/company-department/nestjs-server/src/company/company.model.ts
shashi/company-department/nestjs-server/src/company/company.service.ts
shashi/company-department/nestjs-server/src/database.providers.ts
shashi/company-department/nestjs-server/src/department/company-department.entity.ts
shashi/company-department/nestjs-server/src/department/department.entity.ts

nestjs associations

---

shashi/company-department/client/package-lock.json
shashi/company-department/client/package.json
shashi/company-department/client/src/app/app-routing.module.ts
shashi/company-department/client/src/app/app.module.ts
shashi/company-department/client/src/app/components/company-list/company-list.component.ts
shashi/company-department/client/src/app/components/create-company/create-company.component.ts
shashi/company-department/client/src/app/components/create-department/create-department.component.html
shashi/company-department/client/src/app/components/create-department/create-department.component.ts
shashi/company-department/client/src/app/models/company.model.ts
shashi/company-department/client/src/app/models/department.model.ts

multiselect dropdown code commit pr

multiselect dropdown code commit

---

shashi/student-task/.gitignore
shashi/student-task/client/.gitignore
shashi/student-task/server/.gitignore

student task initial commit pr

student task initial commit

---

shashi/student-task/client/src/app/app-routing.module.ts
shashi/student-task/client/src/app/app.module.ts
shashi/student-task/client/src/app/components/create-school/create-school.component.html
shashi/student-task/client/src/app/components/create-school/create-school.component.ts
shashi/student-task/client/src/app/components/create-student/create-student.component.html
shashi/student-task/client/src/app/components/create-student/create-student.component.ts
shashi/student-task/client/src/app/components/create-teacher/create-teacher.component.html
shashi/student-task/client/src/app/components/create-teacher/create-teacher.component.ts
shashi/student-task/client/src/app/components/file-upload-download/file-upload-download.component.html
shashi/student-task/client/src/app/components/file-upload-download/file-upload-download.component.spec.ts
shashi/student-task/client/src/app/components/file-upload-download/file-upload-download.component.ts
shashi/student-task/client/src/app/components/school-listing/school-listing.component.html
shashi/student-task/client/src/app/components/school-listing/school-listing.component.ts
shashi/student-task/client/src/app/components/student-listing/student-listing.component.html
shashi/student-task/client/src/app/components/student-listing/student-listing.component.ts
shashi/student-task/client/src/app/models/image.model.ts
shashi/student-task/client/src/app/models/student.model.ts
shashi/student-task/client/src/app/services/student-task-service.ts
shashi/student-task/server/src/app.module.ts
shashi/student-task/server/src/fileupload-Download/file.controller.ts
shashi/student-task/server/src/fileupload-Download/file.entity.ts
shashi/student-task/server/src/fileupload-Download/file.module.ts
shashi/student-task/server/src/fileupload-Download/file.provider.ts
shashi/student-task/server/src/fileupload-Download/file.service.ts
shashi/student-task/server/src/school/school.controller.ts
shashi/student-task/server/src/school/school.service.ts
shashi/student-task/server/src/student/student.entity.ts
shashi/student-task/server/src/teacher/teacher.controller.ts
shashi/student-task/server/src/teacher/teacher.service.ts

Shashi student/edit school

---

shashi/student-task/client/src/app/app.module.ts
shashi/student-task/client/src/app/components/create-student/create-student.component.html
shashi/student-task/client/src/app/components/create-student/create-student.component.ts
shashi/student-task/client/src/app/components/create-teacher/create-teacher.component.html
shashi/student-task/client/src/app/components/create-teacher/create-teacher.component.ts
shashi/student-task/client/src/app/components/file-upload-download/file-upload-download.component.html
shashi/student-task/client/src/app/components/file-upload-download/file-upload-download.component.spec.ts
shashi/student-task/client/src/app/components/file-upload-download/file-upload-download.component.ts
shashi/student-task/client/src/app/components/school-listing/school-listing.component.html
shashi/student-task/client/src/app/components/school-listing/school-listing.component.ts
shashi/student-task/client/src/app/components/student-listing/student-listing.component.html
shashi/student-task/client/src/app/components/student-listing/student-listing.component.ts
shashi/student-task/client/src/app/models/image.model.ts
shashi/student-task/client/src/app/models/student.model.ts
shashi/student-task/client/src/app/services/student-task-service.ts
shashi/student-task/server/src/app.module.ts
shashi/student-task/server/src/fileupload-Download/file.controller.ts
shashi/student-task/server/src/fileupload-Download/file.entity.ts
shashi/student-task/server/src/fileupload-Download/file.module.ts
shashi/student-task/server/src/fileupload-Download/file.provider.ts
shashi/student-task/server/src/fileupload-Download/file.service.ts
shashi/student-task/server/src/student/student.entity.ts
shashi/student-task/server/src/teacher/teacher.controller.ts
shashi/student-task/server/src/teacher/teacher.service.ts

Shashi student/fileupload

---

shashi/student-task/vuejs/package-lock.json
shashi/student-task/vuejs/package.json
shashi/student-task/vuejs/src/App.vue
shashi/student-task/vuejs/src/components/AddSchool.vue
shashi/student-task/vuejs/src/components/AddStudent.vue
shashi/student-task/vuejs/src/components/AddTeacher.vue
shashi/student-task/vuejs/src/components/EditSchool.vue
shashi/student-task/vuejs/src/components/SchoolList.vue
shashi/student-task/vuejs/src/components/StudentList.vue
shashi/student-task/vuejs/src/main.ts
shashi/student-task/vuejs/src/router.ts
shashi/student-task/vuejs/src/services/studentservice.ts

vuesjs form-input bindings,list rendering,event handiling(ex:@click)  code pr link

vuesjs code commit

---

shashi/student-task/vuejs/package-lock.json
shashi/student-task/vuejs/package.json
shashi/student-task/vuejs/src/App.vue
shashi/student-task/vuejs/src/components/AddSchool.vue
shashi/student-task/vuejs/src/components/AddStudent.vue
shashi/student-task/vuejs/src/components/AddTeacher.vue
shashi/student-task/vuejs/src/components/Charts.ts
shashi/student-task/vuejs/src/components/EditSchool.vue
shashi/student-task/vuejs/src/components/EditStudent.vue
shashi/student-task/vuejs/src/components/EditTeacher.vue
shashi/student-task/vuejs/src/components/SchoolList.vue
shashi/student-task/vuejs/src/components/StudentList.vue
shashi/student-task/vuejs/src/components/TeacherList.vue
shashi/student-task/vuejs/src/main.ts
shashi/student-task/vuejs/src/router.ts
shashi/student-task/vuejs/src/services/studentservice.ts
shashi/student-task/vuejs/src/types/school.ts
shashi/student-task/vuejs/src/types/student.ts

vuejs code commit map,search, data binding , delete pr

vuejs code commit multiselect dropdown, checkboxes, radio buttons

---

druthvik/StudentManagement/client-reactjs/src/components/school/schoolchart.component.tsx

charts fix

---

harsha/School-Teacher-Student/client-ReactJS/package-lock.json
harsha/School-Teacher-Student/client-ReactJS/package.json
harsha/School-Teacher-Student/client-ReactJS/src/App.css
harsha/School-Teacher-Student/client-ReactJS/src/App.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/charts.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/school/add-school.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/school/data-table.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/school/edit-school.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/school/school-list.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/student/add-student.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/student/edit-student.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/student/student-list.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/teacher/add-teacher.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/teacher/edit-teacher.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/components/teacher/teacher-list.component.tsx
harsha/School-Teacher-Student/client-ReactJS/src/services/school.service.tsx
harsha/School-Teacher-Student/client-ReactJS/src/services/student.service.tsx
harsha/School-Teacher-Student/client-ReactJS/src/services/teacher.service.tsx
harsha/School-Teacher-Student/client-ReactJS/src/types/school.type.tsx
harsha/School-Teacher-Student/client-ReactJS/src/types/student.type.tsx
harsha/School-Teacher-Student/client-ReactJS/src/types/teacher.type.tsx
harsha/School-Teacher-Student/server/src/main/java/com/example/manytomanymapping/controller/StudentController.java
harsha/School-Teacher-Student/server/src/main/java/com/example/manytomanymapping/controller/TeacherController.java
harsha/School-Teacher-Student/server/src/main/java/com/example/manytomanymapping/models/Student.java

Harsha commit on file upload and fixed issue in charts

---

shashi/student-task/vuejsdashboard/src/components/DashboardLayout.vue
shashi/student-task/vuejsdashboard/src/components/Header.vue
shashi/student-task/vuejsdashboard/src/router/index.ts
shashi/student-task/vuejsdashboard/src/views/Forms.vue
shashi/student-task/vuejsdashboard/src/views/Tables.vue

vuejs dashboard search and pagination code pr

vuejs dashboard search and pagination code commit

---

shashi/student-task/vuejsdashboard/package-lock.json
shashi/student-task/vuejsdashboard/package.json
shashi/student-task/vuejsdashboard/public/index.html
shashi/student-task/vuejsdashboard/src/components/DashboardLayout.vue
shashi/student-task/vuejsdashboard/src/components/Header.vue
shashi/student-task/vuejsdashboard/src/router/index.ts
shashi/student-task/vuejsdashboard/src/studentservice.ts
shashi/student-task/vuejsdashboard/src/views/EditSchoolForm.vue
shashi/student-task/vuejsdashboard/src/views/Forms.vue
shashi/student-task/vuejsdashboard/src/views/Login.vue
shashi/student-task/vuejsdashboard/src/views/School.vue
shashi/student-task/vuejsdashboard/src/views/Tables.vue
shashi/student-task/vuejsdashboard/yarn.lock

Shashi vuejs dashboard drag&drop in edit school scenario pr

Shashi vuejs dashboard/drag&drop

---

shashi/student-task/vuejsdashboard/package-lock.json
shashi/student-task/vuejsdashboard/package.json
shashi/student-task/vuejsdashboard/public/index.html
shashi/student-task/vuejsdashboard/src/studentservice.ts
shashi/student-task/vuejsdashboard/src/views/Forms.vue
shashi/student-task/vuejsdashboard/src/views/School.vue
shashi/student-task/vuejsdashboard/src/views/Tables.vue
shashi/student-task/vuejsdashboard/yarn.lock

vuejs drag and drop code commit
